---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

vars:
  BREWFILE: "{{.ROOT_DIR}}/.taskfiles/workstation/Brewfile"
  DOCKERCONFIGFILE: "{{.ROOT_DIR}}/.taskfiles/workstation/docker.json"

tasks:

  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{.BREWFILE}}
    preconditions:
      - { msg: "Missing Homebrew", sh: "command -v brew" }
      - { msg: "Missing Brewfile", sh: "test -f {{.BREWFILE}}" }

  direnv:
    desc: Run direnv hooks
    cmd: direnv allow .
    status:
      - "[[ $(direnv status --json | jq '.state.foundRC.allowed') == 0 ]]"
      - "[[ $(direnv status --json | jq '.state.loadedRC.allowed') == 0 ]]"
