---
name: "Scheduled: Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      apps:
        description: "Apps (ex: radarr,sonarr)"
        required: false
        type: string
        default: "all"
      force:
        description: "Rebuild images regardless of whether version has changed"
        type: boolean
        default: false
        required: true
  schedule:
    - cron: "0 * * * *"

jobs:
  build-images:
    name: Build Images
    uses: ./.github/workflows/workflow_call-build_images.yaml
    permissions:
      contents: read
      packages: write
    with:
      appsToBuild: ${{ inputs.apps }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs:
      - build-images
    uses: ./.github/workflows/workflow_call-render-readme.yaml
    secrets: inherit
